/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classesGerenciador.Categoria;
import classesGerenciador.ContasUsuarios;
import classesGerenciador.OrigemRenda;
import classesGerenciador.Transacao;
import classesGerenciador.Usuario;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import javax.swing.*;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.PieDataset;
import projeto.gerenciador.financeiro.ControleTelas;
import java.time.YearMonth;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author Bruno Eduardo <https://github.com/brnduol>
 */
public class TelaGrafico1 extends javax.swing.JFrame {
    private ContasUsuarios contaUsuarios;
    private Usuario contaAtual;
    private ControleTelas controleTelas;
    
    /**
     * Creates new form TelaGrafico1
     */
    public TelaGrafico1() {
        contaUsuarios = ContasUsuarios.getInstance();
        contaAtual = contaUsuarios.conta();
        controleTelas = ControleTelas.getInstance(); 
        initComponents();
        
        this.setLocationRelativeTo(null);
        setSize(903, 726);  
        jPanel1.setLayout(new java.awt.BorderLayout()); 
        

        carregarCategoriaOrigemRenda();
        
        // Chama a função de atualizar o gráfico ao iniciar a tela, passando a data atual
        String dataAtual = LocalDate.now().format(DateTimeFormatter.ofPattern("MM/yyyy"));
        txtDataGrafico1.setText(dataAtual);
        // Configura a ComboBox para a opção "Receitas/Despesas"
        cbCategoriaOrigemRenda.setSelectedItem("Receitas/Despesas");

        btnAtualizarActionPerformed(null); // Atualiza o gráfico com o mês atual
        
        
    }
    
    
     
     public void carregarCategoriaOrigemRenda(){
         //Remover os itens da ComboBox
         cbCategoriaOrigemRenda.removeAllItems();

         cbCategoriaOrigemRenda.addItem("Tipo");
         
         String[] tipos = {"Categoria", "Receitas/Despesas"};
         
         for (String tipo : tipos) {
             cbCategoriaOrigemRenda.addItem(tipo);
         }
     }
    
     
     private YearMonth validarEConverterData(String dataString) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM/uuuu")
                                                       .withResolverStyle(ResolverStyle.STRICT);
        try {
            return YearMonth.parse(dataString, formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "Data inválida: " + dataString + ". Use o formato MM/aaaa.", "Erro", JOptionPane.ERROR_MESSAGE);
            return null; // Retorna null se inválida
        }
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cbCategoriaOrigemRenda = new javax.swing.JComboBox<>();
        txtDataGrafico1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuGrafico = new javax.swing.JMenu();
        jmPrincipal = new javax.swing.JMenuItem();
        btContasGrafico = new javax.swing.JMenuItem();
        btHistoricoGrafico = new javax.swing.JMenuItem();
        btCategoriasGrafico = new javax.swing.JMenuItem();
        btSairGrafico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        cbCategoriaOrigemRenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCategoriaOrigemRenda.setToolTipText("Selecione o tipo");
        cbCategoriaOrigemRenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaOrigemRendaActionPerformed(evt);
            }
        });

        txtDataGrafico1.setText("mm/aaaa");
        txtDataGrafico1.setToolTipText("Insira a data");
        txtDataGrafico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataGrafico1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Data:");

        menuGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1485477024-menu_78574.png"))); // NOI18N
        menuGrafico.setText("Menu");

        jmPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/3643769-building-home-house-main-menu-start_113416 (1).png"))); // NOI18N
        jmPrincipal.setText("Tela principal");
        jmPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPrincipalActionPerformed(evt);
            }
        });
        menuGrafico.add(jmPrincipal);

        btContasGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/4634994-cloud_122540 (1).png"))); // NOI18N
        btContasGrafico.setText("Contas");
        btContasGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContasGraficoActionPerformed(evt);
            }
        });
        menuGrafico.add(btContasGrafico);

        btHistoricoGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/historical_3107 (1).png"))); // NOI18N
        btHistoricoGrafico.setText("Historico");
        btHistoricoGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistoricoGraficoActionPerformed(evt);
            }
        });
        menuGrafico.add(btHistoricoGrafico);

        btCategoriasGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/graph_progress_chart_charts_analytics_bars_icon_124175.png"))); // NOI18N
        btCategoriasGrafico.setText("Categorias");
        btCategoriasGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoriasGraficoActionPerformed(evt);
            }
        });
        menuGrafico.add(btCategoriasGrafico);

        btSairGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/4115235-exit-logout-sign-out_114030.png"))); // NOI18N
        btSairGrafico.setText("Sair");
        btSairGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairGraficoActionPerformed(evt);
            }
        });
        menuGrafico.add(btSairGrafico);

        jMenuBar1.add(menuGrafico);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtDataGrafico1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(cbCategoriaOrigemRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDataGrafico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCategoriaOrigemRenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                        
    private void mostrarGrafico(DefaultPieDataset dataset) {
        // Criar o gráfico de pizza
        JFreeChart chart = ChartFactory.createPieChart(
            "Gráfico", // Título do gráfico
            dataset, // Dataset com os dados
            true, // Exibir legenda
            true, // Exibir tooltip
            false // Exibir URLs
        );

        // Customizar o gráfico de pizza
        PiePlot plot = (PiePlot) chart.getPlot();

        plot.setLabelGenerator(new StandardPieSectionLabelGenerator() {
            @Override
            public String generateSectionLabel(PieDataset dataset, Comparable key) {
                // Pega o valor da transação associada à categoria
                int valor = dataset.getValue(key).intValue();

                // Verifica se o valor é de Despesa
                if (key.toString().contains("Despesa")) {
                    // Exibe o valor como positivo com uma descrição indicando despesa
                    return key + ": " + "-" + valor + ")";
                } else {
                    return key + ": " + valor;
                }
            }
        });

        // Adicionar o gráfico ao painel (jPanel1)
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(710, 450));

        // Limpar o painel antes de adicionar um novo gráfico
        jPanel1.removeAll();
        jPanel1.add(chartPanel, java.awt.BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }


    
    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
                                                                                                          
                                                
        String dataTexto = txtDataGrafico1.getText().trim();
        YearMonth dataSelecionada = validarEConverterData(dataTexto);

        if (dataTexto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, insira a data no formato MM/AAAA.", "Mensagem", JOptionPane.PLAIN_MESSAGE);
            return;
        }

        if (dataSelecionada == null) {
            JOptionPane.showMessageDialog(null, "Formato de data inválido. Use MM/AAAA.", "Mensagem", JOptionPane.PLAIN_MESSAGE);
            return; // Interrompe a execução se a data for inválida
        }

        int mesSelecionado = dataSelecionada.getMonthValue();
        int anoSelecionado = dataSelecionada.getYear();

        String selectedCategoriaOrigemRenda = (String) cbCategoriaOrigemRenda.getSelectedItem();

        // Validação adicional para o campo de categoria
        if (selectedCategoriaOrigemRenda == null || selectedCategoriaOrigemRenda.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma categoria.", "Mensagem", JOptionPane.PLAIN_MESSAGE);
            return;
        }

        // Criar o dataset do gráfico
        DefaultPieDataset dataset = new DefaultPieDataset();

        if (selectedCategoriaOrigemRenda.equals("Categoria")) {
            // Iterar pelas categorias de despesas (Categoria)
            for (Categoria categoria : contaAtual.getCategorias()) {
                double somaTransacoes = 0;

                for (Transacao transacao : categoria.getTransacoes()) {
                    int anoTransacao = transacao.getData().getYear();
                    int mesTransacao = transacao.getData().getMonthValue();

                    if (anoTransacao == anoSelecionado && mesTransacao == mesSelecionado) {
                        somaTransacoes += transacao.getValor();
                    }
                }

                if (somaTransacoes != 0) {
                    dataset.setValue("Despesa - " + categoria.getNomeCategoria(), Math.abs(somaTransacoes));
                    System.out.println("Despesa - Categoria: " + categoria.getNomeCategoria() + " | Soma Transações: " + somaTransacoes);
                }
            }

            for (OrigemRenda origemRenda : contaAtual.getOrigemRendas()) {
                double somaTransacoes = 0;

                for (Transacao transacao : origemRenda.getTransacoes()) {
                    int anoTransacao = transacao.getData().getYear();
                    int mesTransacao = transacao.getData().getMonthValue();

                    if (anoTransacao == anoSelecionado && mesTransacao == mesSelecionado) {
                        somaTransacoes += transacao.getValor();
                    }
                }

                if (somaTransacoes != 0) {
                    dataset.setValue("Receita - " + origemRenda.getNomeOrigemRenda(), somaTransacoes);
                    System.out.println("Receita - Origem: " + origemRenda.getNomeOrigemRenda() + " | Soma Transações: " + somaTransacoes);
                }
            }

        } else if (selectedCategoriaOrigemRenda.equals("Receitas/Despesas")) { 
            double totalReceitas = 0;
            double totalDespesas = 0;

            for (Transacao transacao : contaAtual.getTransacoes()) {
                int anoTransacao = transacao.getData().getYear();
                int mesTransacao = transacao.getData().getMonthValue();

                if (anoTransacao == anoSelecionado && mesTransacao == mesSelecionado) {
                    double valor = transacao.getValor();

                    if (valor > 0) {
                        totalReceitas += valor;
                    } else {
                        totalDespesas += Math.abs(valor);
                    }
                }
            }

            int receitasInteiras = (int) Math.round(totalReceitas);
            int despesasInteiras = (int) Math.round(totalDespesas);

            if (receitasInteiras > 0) {
                dataset.setValue("Receitas", receitasInteiras);
            }
            if (despesasInteiras > 0) {
                dataset.setValue("Despesas", despesasInteiras);
            }
        }

        if (dataset.getItemCount() == 0) {
            JOptionPane.showMessageDialog(null, "Não há transações para o período selecionado.", "Mensagem", JOptionPane.PLAIN_MESSAGE);
        } else {
            mostrarGrafico(dataset);
        }
    

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btContasGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContasGraficoActionPerformed
        // Abrir a tela principal
        controleTelas.getTelaContas().setVisible(true);
        this.dispose(); // Fecha a tela atual
        
        
    }//GEN-LAST:event_btContasGraficoActionPerformed

    private void btHistoricoGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistoricoGraficoActionPerformed
        // Abrir a tela de histórico
        controleTelas.getTelaHistorico().setVisible(true);
        this.dispose(); // Fecha a tela atual
    }//GEN-LAST:event_btHistoricoGraficoActionPerformed

    private void btCategoriasGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCategoriasGraficoActionPerformed
        controleTelas.getTelaCategoria().setVisible(true);
        dispose();
    }//GEN-LAST:event_btCategoriasGraficoActionPerformed

    private void btSairGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairGraficoActionPerformed
        contaUsuarios.sairConta();
        controleTelas.getTelaLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btSairGraficoActionPerformed

    private void jmPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPrincipalActionPerformed
        // Abrir a tela principal
        controleTelas.getTelaPrincipal().setVisible(true);
        this.dispose(); // Fecha a tela atual
    }//GEN-LAST:event_jmPrincipalActionPerformed

    private void cbCategoriaOrigemRendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaOrigemRendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriaOrigemRendaActionPerformed

    private void txtDataGrafico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataGrafico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataGrafico1ActionPerformed

                    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGrafico1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGrafico1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGrafico1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGrafico1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()  {
            public void run() {
                new TelaGrafico1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btCategoriasGrafico;
    private javax.swing.JMenuItem btContasGrafico;
    private javax.swing.JMenuItem btHistoricoGrafico;
    private javax.swing.JMenuItem btSairGrafico;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JComboBox<String> cbCategoriaOrigemRenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmPrincipal;
    private javax.swing.JMenu menuGrafico;
    private javax.swing.JTextField txtDataGrafico1;
    // End of variables declaration//GEN-END:variables
}
